export { default as Blog } from './blog/blog'
export { default as Features } from './features/features'
export { default as Footer } from './footer/footer'
export { default as Header } from './header/header'
export { default as Posibillities } from './posibillities/posibillities'
export { default as Whatgpt } from './whatgpt/whatgpt'
